services:
  fedora:
    environment:
      GOCOVERDIR: "/app/coverage/int/fedora"
    build:
      context: .
      dockerfile: .docker/Fedora.dockerfile
    volumes:
      - "./coverage/int/fedora:/app/coverage/int/fedora"