name: CI
on:
  push: 
jobs:
  test:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true
      - run: make build
      - run: make unit
      - run: docker compose up
        if: runner.os == 'ubuntu-latest'
      - run: tar czf ${{runner.os}}.tar.gz ./coverage
      - uses: actions/upload-artifact@master
        with:
          name: coverage-${{matrix.os}}
          path: ${{runner.os}}.tar.gz
  report:
    runs-on: ubuntu-latest
    needs: ['test']
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: ./coverage
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      