name: CI
on:
  push: 
jobs:
  test:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    env:
      GOCOVERDIR: ./coverage/int/${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true
      - run: make buildcov
      - run: mkdir -p $GOCOVERDIR
      - run: make unit
      - run: make integration
      - run: docker compose up
        if: runner.os == 'Linux'
      - run: tar czf ${{runner.os}}.tar.gz ./coverage
      - uses: actions/upload-artifact@master
        with:
          name: coverage-${{matrix.os}}
          path: ${{runner.os}}.tar.gz
  report:
    runs-on: ubuntu-latest
    needs: ['test']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true
      - uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: ./coverage
      - run: |
          mkdir linux && tar xvf coverage/coverage-ubuntu-latest/Linux.tar.gz -C linux
          mkdir mac && tar xvf coverage/coverage-macos-latest/macOS.tar.gz -C mac
# go tool covdata textfmt -i=./linux/coverage/unit,./mac/coverage/unit,./linux/coverage/int/fedora,./linux/coverage/int/ubuntu-latest -o coverage.txt && sed -i 2,3d coverage.txt
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      