name: CI
on:
  push: 
jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true
      - if: runner.os == 'macos'
        run: |
          brew install --cask docker
      - run: make build
      - run: make unit
      - run: docker compose up
      - run: make combine-coverage
      - run: make coverage-report